# Generated by Django 3.0.7 on 2020-09-11 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200624_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='amount',
            new_name='value',
        ),
    ]
