# Generated by Django 3.0.7 on 2020-09-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200911_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='value',
            new_name='worth',
        ),
    ]
